'use strict';
const $=id=>document.getElementById(id),music=$('music'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
function musicState(){const playing=!music.paused;$('music-toggle').setAttribute('aria-pressed',String(playing));$('music-toggle').setAttribute('aria-label',playing?'Pausar música':'Reproducir música');$('music-toggle').innerHTML=(playing?'Ⅱ':'♫')+' <span>Música</span>'}
music.addEventListener('play',musicState);music.addEventListener('pause',musicState);
$('music-toggle').addEventListener('click',()=>music.paused?music.play().catch(musicState):music.pause());
$('open').addEventListener('click',()=>{$('open').disabled=true;music.volume=.55;music.play().catch(musicState);$('cover').classList.add('opening');setTimeout(()=>{$('cover').hidden=true;$('invitation').hidden=false;$('music-toggle').hidden=false;document.body.classList.remove('sealed');scrollTo(0,0);document.querySelector('.hero h2').focus({preventScroll:true});if('IntersectionObserver'in window&&!reduced.matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.05});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('reveal-ready');observer.observe(el)})}},reduced.matches?0:850)});
if(!reduced.matches)for(let i=0;i<18;i++){const light=document.createElement('i');light.className='light';light.style.cssText=`--x:${(i*37+7)%100}%;--y:${(i*23+8)%100}%;--speed:${5+i%4}s;--delay:${-i*1.3}s`;$('lights').append(light)}
function countdown(){const diff=new Date('2026-10-15T19:00:00-04:00')-Date.now();if(diff<=0){$('countdown').textContent='La novenaria ha comenzado. Unidos en oración.';return}const values=[Math.floor(diff/86400000),Math.floor(diff/3600000)%24,Math.floor(diff/60000)%60,Math.floor(diff/1000)%60];$('countdown').innerHTML=values.map((n,i)=>`<div><strong>${String(n).padStart(2,'0')}</strong><span>${['DÍAS','HORAS','MINUTOS','SEGUNDOS'][i]}</span></div>`).join('')}
countdown();setInterval(countdown,1000);
const photos=[['assets/retrato-traje.jpeg','Una vida que dejó huella'],['assets/recuerdo-sereno.jpeg','La calma de tu compañía'],['assets/sonrisa-familiar.webp','El regalo de tu sonrisa'],['assets/sombrero.webp','Así te llevamos en el alma']];let current=0,returnFocus=null;
function showPhoto(){const [src,caption]=photos[current];$('large-photo').src=src;$('large-photo').alt='Carlos Caballero Santiesteban · '+caption;$('photo-caption').textContent=`${current+1} / ${photos.length} · ${caption}`}
document.querySelectorAll('[data-photo]').forEach(button=>button.addEventListener('click',()=>{returnFocus=button;current=Number(button.dataset.photo);showPhoto();$('photo-dialog').showModal()}));
$('close-photo').addEventListener('click',()=>$('photo-dialog').close());$('photo-dialog').addEventListener('close',()=>returnFocus?.focus());$('photo-dialog').addEventListener('click',event=>{if(event.target===$('photo-dialog')){const r=$('photo-dialog').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)$('photo-dialog').close()}});
function movePhoto(step){current=(current+step+photos.length)%photos.length;showPhoto()}
$('previous-photo').addEventListener('click',()=>movePhoto(-1));$('next-photo').addEventListener('click',()=>movePhoto(1));$('photo-dialog').addEventListener('keydown',e=>{if(e.key==='ArrowRight')movePhoto(1);if(e.key==='ArrowLeft')movePhoto(-1)});
let lit=false;try{lit=localStorage.getItem('carlos-memoria-vela')==='1'}catch{}
function candleState(){$('candle').classList.toggle('lit',lit);$('light-candle').setAttribute('aria-pressed',String(lit));$('light-candle').textContent=lit?'Apagar mi vela':'Encender una vela';$('candle-message').textContent=lit?'Tu luz me acompaña. Gracias por mantener vivo mi recuerdo.':'Aunque la luz se apague, nuestro amor permanece.'}
candleState();$('light-candle').addEventListener('click',()=>{lit=!lit;candleState();try{localStorage.setItem('carlos-memoria-vela',lit?'1':'0')}catch{}});
function publicLink(){if(['localhost','127.0.0.1',''].includes(location.hostname)||location.protocol==='file:'){$('share-status').textContent='Podrás compartir el enlace cuando la invitación esté publicada.';return null}return location.href.split('#')[0]}
async function copyLink(){const url=publicLink();if(!url)return;try{await navigator.clipboard.writeText(url);$('share-status').textContent='Enlace copiado para compartir con la familia.'}catch{$('share-status').textContent='Puedes copiar el enlace desde la barra del navegador.'}}
$('copy-link').addEventListener('click',copyLink);$('share').addEventListener('click',async()=>{const url=publicLink();if(!url)return;try{if(navigator.share)await navigator.share({title:'En memoria del Dr. Carlos Caballero Santiesteban',text:'Con amor eterno, les invitamos a acompañarnos en oración y a compartir este recuerdo.',url});else await copyLink()}catch(e){if(e.name!=='AbortError')$('share-status').textContent='Utiliza «Copiar enlace» para compartir este recuerdo.'}});
